/* Shared longitudinal suspension explanation and side-view illustration. */
window.DriftAnti=(()=>{
  const M=DriftModel,L='#c6f36b',C='#65d8ef',O='#ffa66b',G='#99a7b2';
  const f=(n,d=1)=>(Math.abs(n)<.5*10**(-d)?0:Number(n)).toLocaleString('ru-RU',{minimumFractionDigits:d,maximumFractionDigits:d}),sg=n=>(n>=.05?'+':'')+f(n);
  const text=(x,y,t,c=G,size=16,anchor='start')=>`<text x="${x}" y="${y}" fill="${c}" font-size="${size}" text-anchor="${anchor}">${t}</text>`;
  const line=(x,y,a,b,c,d='')=>`<path d="M${x} ${y}L${a} ${b}" stroke="${c}" stroke-width="2" fill="none" ${d?'stroke-dasharray="6 4"':''}/>`;
  const arrow=(x,y,a,b,c)=>{const angle=Math.atan2(b-y,a-x);return line(x,y,a,b,c)+`<path d="M${a-8*Math.cos(angle-.5)} ${b-8*Math.sin(angle-.5)}L${a} ${b}L${a-8*Math.cos(angle+.5)} ${b-8*Math.sin(angle+.5)}" fill="none" stroke="${c}" stroke-width="2"/>`};
  function visual(s,reference=null){
    const p=M.pitchResponse(s),zero=M.pitchResponse(reference||{...s,frontAntiDive:0,rearAntiSquat:0}),scale=400/s.wheelbase*6;
    const y=v=>139+M.clamp(v,-75,75)*scale;
    const body=(q,c,dash)=>`<path d="M80 ${y(q.frontTravel)}L560 ${y(q.rearTravel)}L540 ${y(q.rearTravel)-28}L130 ${y(q.frontTravel)-28}Z" stroke="${c}" stroke-width="3" fill="${dash?'none':'#17242a'}" ${dash?'stroke-dasharray="6 5"':''}/>`;
    let out=text(28,28,'Side view · перед слева ←',G,17)+text(612,28,`${sg(p.ax/9.81)} g`,C,20,'end')+line(40,249,600,249,G);
    out+=body(zero,O,true)+body(p,L,false);
    [[120,p.frontTravel,'Front'],[520,p.rearTravel,'Rear']].forEach(([x,travel,label])=>{
      const top=y(travel)+3,bottom=204;let coil=`M${x} ${top}`;for(let j=1;j<10;j++)coil+=`L${x+(j%2?7:-7)} ${top+(bottom-top)*j/10}`;coil+=`L${x} ${bottom}`;
      out+=`<path d="${coil}" fill="none" stroke="${L}" stroke-width="2"/><circle cx="${x}" cy="218" r="30" fill="#142127" stroke="${G}" stroke-width="3"/>`+text(x,275,label,G,17,'middle')+text(x,300,`${sg(travel)} mm`,L,21,'middle');
    });
    const cx=300,cy=(y(p.frontTravel)+y(p.rearTravel))/2-14;
    out+=`<circle cx="${cx}" cy="${cy}" r="6" fill="${C}"/>`+text(cx,cy-15,'CG',C,14,'middle');
    if(Math.abs(p.ax)>.001)out+=arrow(cx,80,cx-Math.sign(p.ax)*85,80,C)+text(cx,61,p.ax<0?'Braking':'Acceleration',C,17,'middle');
    if(p.frontGeometry>1)out+=arrow(173,199,173,155,L)+text(188,180,'Geo ↑',L,14);
    if(p.rearGeometry>1)out+=arrow(468,199,468,155,L)+text(395,180,'Geo ↑',L,14);
    out+=text(320,224,`Body pitch ${sg(p.pitch)}°`,C,18,'middle')+text(320,328,reference?'Ход ×6 · оранжевый пунктир — сохранённые настройки':'Ход ×6 · оранжевый пунктир — 0% Anti при тех же условиях',G,13,'middle');
    return `<svg viewBox="0 0 640 345" role="img" aria-label="Клевок и приседание кузова: текущие Anti-dive и Anti-squat против ${reference?'сохранённых настроек':'0 процентов'}">${out}</svg>`;
  }
  function explanation(s){
    const p=M.pitchResponse(s),braking=p.ax<-.001,drive=p.ax>.001;
    if(!braking&&!drive)return 'Без продольной силы Anti-dive и Anti-squat не создают реакцию. Выберите Braking или Acceleration, затем меняйте Anti %. Плюс Wheel travel — сжатие, минус — отбой.';
    return `${braking?'Передняя':'Задняя'} ось получает дополнительно ${f(Math.abs(p.limitedTransfer)/1000,2)} kN. Anti ${braking?'dive':'squat'} направляет через геометрию ${f((braking?p.frontGeometry:p.rearGeometry)/1000,2)} kN; на пружины этой оси остаётся ${sg((braking?p.frontElastic:p.rearElastic)/1000)} kN. Перенос веса сохраняется. ${braking?'Rear anti-squat здесь не активен: нет тяги.':'Front anti-dive здесь не активен: нет тормозной силы спереди.'}${p.travelLimited||p.loadLimited?' Достигнута граница учебной модели: на схеме ход ограничен ±75 mm; отбойники не рассчитаны.':''}`;
  }
  function details(s){
    const p=M.pitchResponse(s),r=M.calculate(s),old=M.calculate({...s,frontAntiDive:0,rearAntiSquat:0});
    const row=(label,a,b,unit='kN',digits=2)=>`<tr><th>${label}</th><td>${f(a,digits)} ${unit}</td><td>${f(b,digits)} ${unit}</td></tr>`;
    return `<h3>Куда идёт нагрузка</h3><div class="anti-table-wrap"><table class="anti-table"><thead><tr><th></th><th>Front</th><th>Rear</th></tr></thead><tbody>${row('Axle load',p.frontLoad/1000,p.rearLoad/1000)}${row('Geometry reaction',p.frontGeometry/1000,p.rearGeometry/1000)}${row('Spring load change',p.frontElastic/1000,p.rearElastic/1000)}${row('Wheel rate',p.frontRate,p.rearRate,'N/mm',1)}${row('Pitch travel',p.frontTravel,p.rearTravel,'mm',1)}</tbody></table></div><p>Geometry reaction и Spring load change — добавки к исходной статической нагрузке. 100% убирает добавочное сжатие выбранной оси в эталонном опыте, но другая ось всё ещё может двигаться. Более 100% может дать отбой.</p><h3>Front Bump steer</h3><p>Anti-dive → Pitch travel → Total wheel travel → Toe change. Сама кривая Toe change от Anti % не меняется.</p><div class="anti-table-wrap"><table class="anti-table"><thead><tr><th></th><th>LF</th><th>RF</th></tr></thead><tbody>${row('Total wheel travel',r.wheels[0].travel,r.wheels[1].travel,'mm',1)}${row('Toe change · 0% Anti',old.wheels[0].toeChange,old.wheels[1].toeChange,'°',3)}${row('Toe change · сейчас',r.wheels[0].toeChange,r.wheels[1].toeChange,'°',3)}</tbody></table></div><p>${s.bumpToe===0&&s.reboundToe===0?'Кривая Bump steer сейчас нулевая: ход меняется, направление колёс от него не меняется.':'«+» Toe change — Toe-in, «−» — Toe-out. LF и RF получают зеркальные добавки к Steering angle.'} Total travel также включает ручной Wheel input и Body roll.</p><p>Front anti-dive задан при Front brake bias 65%. Сейчас bias ${f(s.frontBrakeBias??65,0)}%: эффективный Anti-dive ${p.frontEffective===null?'— (нет торможения)':f(p.frontEffective,0)+'%'}. Эквивалентная геометрическая реакция: Front ${f(p.frontRatio,3)} N/N · Rear ${f(p.rearRatio,3)} N/N.</p>`;
  }
  const help=`<h3>Front anti-dive</h3><p>При торможении передняя ось догружается. Геометрия MacPherson может передать часть этой добавочной реакции на кузов через звенья подвески, уменьшая сжатие пружин и клевок. Это свойство кинематики в боковой проекции; Caster сам по себе не задаёт Anti-dive. Для расчёта по реальной машине нужны координаты креплений, CG height, Wheelbase и распределение тормозной силы.</p><h3>Rear anti-squat</h3><p>Под тягой задняя ось догружается. Anti-squat уменьшает добавочное сжатие задних пружин, а выше 100% может заставить заднюю подвеску разжиматься. Это не обещание большего сцепления: реакция на неровности, амортизаторы и реальные характеристики шин здесь не рассчитаны.</p><h3>Как сравнивать</h3><p>Задайте Longitudinal acceleration. Сравните 0%, 50% и 100%: Axle load остаётся прежней, меняются Pitch travel, Body pitch и распределение реакции между геометрией и пружинами. При нулевой кривой Bump steer подруливания не появится. Меняйте Bump toe / Rebound toe, чтобы увидеть эту связь.</p><h3>Границы расчёта</h3><p>Это квазистатическая оценка при заданной силе, не симуляция качания кузова. Достижимость заданного ускорения по сцеплению в этом опыте не проверяется. Масса 1250 kg, CG height 520 mm, передняя развесовка 55%; масса условно сосредоточена на кузове. Передний Wheel rate получается из Front spring rate и Motion ratio. Задняя ось задана эквивалентным Rear wheel rate (исходные 55 N/mm — допущение).</p><p>Rear anti-lift при торможении и Front anti-lift под тягой приняты нулевыми. Нет расчёта координат подвески, изменения Caster/Camber от продольного хода, заднего Toe gain и шин по высоте. Поэтому Rear anti-squat здесь не меняет Rear grip искусственным множителем.</p><p>В Driving target и Free response продольная сила берётся из динамики, а не из ползунка этого опыта. Реакция Anti-dive связана только с реализованной передней тормозной силой; Anti-squat — с задней тягой. Их сглаживание 0,15 s совпадает с переносом нагрузки и не заменяет модель амортизаторов.</p><p><a href="https://race.software/academy/suspension-designer-library/anti-dive-and-anti-lift-and-anti-squat/" target="_blank" rel="noopener">RACE: Anti-properties и реакция N/N</a> · <a href="https://optimumg.com/wp-content/uploads/2024/03/OptimumG-V32N4.pdf" target="_blank" rel="noopener">OptimumG: геометрическая и упругая реакция, Brake distribution</a></p>`;
  return {visual,explanation,details,help};
})();
